---
- hosts: TEST
  remote_user: ciscorelease
  gather_facts: False

  tasks:
  - name: Check disk space for servers
    command: "df -kh"
    changed_when: False
    register: diskspace

  - name: printing the disk space
    debug:
      msg: "{{diskspace.stdout}}"

