---
- hosts: TEST
  tasks:
    - name: Testing user sudo privilege
      command: /usr/bin/sudo -v
      register: sudo_response
      ignore_errors: yes
      tags:
        - pre_check

    - name: Stop further if User doesn't have sudo privilege
      fail: msg="User doesn't have sudo privilege."
      when: sudo_response.rc != 0
      tags:
        - pre_check

    - name: Stop httpd service
      service: name=httpd state=stopped
      tags:
        - stop
      become: yes
 
    - name: Start httpd service
      service: name=httpd state=started
      tags:
        - start
      become: yes


