---
- hosts: TEST
  gather_facts: False
  become: true
  become_user: splunk
  become_method: sudo

  tasks:

  - name: take backup of ticketLogExtractor.py 
    shell: cp /opt/CSCO-CMS/DataExtractor/lib/ticketLogExtractor.py /opt/splunk/

  - name: Check file ticketLogExtractor.py in /opt/splunk
    stat:
      path: /opt/splunk/ticketLogExtractor.py
    register: p

  - debug:
      msg: "File exists..."
    when: p.stat.exists

  - name: copy ticketLogExtractor.py to /tmp folder after backup file confirmed
    copy: src=/etc/ansible/playbooks/ticketLogExtractor.py dest=/tmp owner=splunk group=splunk mode=0755
    when: p.stat.exists
  
  - name: copy file /tmp/ticketLogExtractor.py to /opt/CSCO-CMS/DataExtractor/lib/ticketLogExtractor.py
    shell: cp /tmp/ticketLogExtractor.py /opt/CSCO-CMS/DataExtractor/lib/ticketLogExtractor.py
    
  - name: Check file ticketLogExtractor.py is present in /opt/CSCO-CMS/DataExtractor/lib/
    stat:
      path: /opt/CSCO-CMS/DataExtractor/lib/ticketLogExtractor.py
    register: r
  
  - debug:
      msg: "ticketLogExtractor.py File is present in /opt/CSCO-CMS/DataExtractor/lib/..."
    when: r.stat.exists

  - name: 2nd remove /tmp/ticketLogExtractor.py file
    file: path=/tmp/ticketLogExtractor.py state=absent
    when: r.stat.exists

      
