---
- hosts: TEST
  vars_files: ['credentials.yml']
  remote_user: root
  

  tasks:
   - name: Change ciscorelease password
     user: name=ciscorelease update_password=always password={{ciscorelease_password}}


