---
- hosts: TEST
  gather_facts: True
  become: true
  
  vars_files:
    - var1.yml

  tasks:
    - include: install_apache.yml

    - name: Check apache service
      service: name="{{package_name}}" state=started

