---
- hosts: TEST
  gather_facts: True
  become: true
  
  vars:
    - package_name: "httpd"

  tasks:
    - include: install_apache.yml

    - name: Check apache service
      service: name="{{package_name}}" state=started

