---
- host: all

   tasks:
   
   - name: Import Remi GPG key.
     rpm_key: "key={{ item }} state=present"
     with_items:
       - "http://rpms.famillecollet.com/RPM-GPG-KEY-remi"
   - name: Install Remi repo.
     command: "rpm -Uvh --force {{ item.href }} creates={{ item.creates }}"
     with_items:
       - href: "http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"
         creates: "/etc/yum.repos.d/remi.repo"

   - name: Install EPEL repo.
     yum: name=epel-release state=present

   - name: Ensure firewalld is stopped (since this is a test server).
     service: name=firewalld state=stopped

   - name: Install Node.js and npm.
     yum: name=npm state=present enablerepo=epel

   - name: Install Forever (to run our Node.js app).
     npm: name=forever global=yes state=latest


