---
- hosts: TEST
  gather_facts: False
  vars_files:
    - rpmnames.yml

  tasks:
  - name: Check  RPM verison details
    command: rpm -q --qf "%{VERSION}\n" {{ item }}
    args:
      warn: no
    changed_when: False
    register: r
    with_items: "{{ modules }}"

#  - name: Create the Jinja2 based template
#    template: src=rpm.j2 dest=/tmp/ansible.txt
#    changed_when: False

  - name: RPM version Info
    debug:
      msg: "{% set output = [] %}\
        {% for result in r.results %}\
          {{ output.append( result.item ~ ' verison is: ' ~ result.stdout ) }}\
        {% endfor %}\
      {{ output }}"


