---
- hosts: TEST
  remote_user: ciscorelease
  gather_facts: False

  tasks:
  - name: Check rpm version
    command: rpm -q --qf "%{VERSION}\n" rsyslog
    changed_when: False
    register: rpmversion
 
  - name: printing the rsyslog rpm verison
    debug:
      msg: rsyslog current version is "{{rpmversion.stdout}}"




