---
- hosts: TEST
  gather_facts: False
  become: true
  become_user: splunk
  become_method: su
  vars_files:
    - splunkappnames.yml

  tasks:
  - name: Check  splunk app verison
    shell: cat {{ item }} | grep version | sed 's/[a-z= ]//g'
    changed_when: False
    register: r
    with_items: "{{ modules }}"    

#  - debug:
#      msg: "{{item.item}} verison is {{item.stdout}}"
#   with_items: "{{r.results}}"    

  - name: splunk forwarder app version
    debug:
      msg: "{% set output = [] %}\
        {% for result in r.results %}\
          {{ output.append( result.item ~ ' verison is: ' ~ result.stdout ) }}\
        {% endfor %}\
      {{ output }}"


